version: "2"

services:

    namenode:
        image: bde2020/hadoop-namenode:1.1.0-hadoop2.7.1-java8
        container_name: namenode
        volumes:
          - hadoop_namenode:/hadoop/dfs/name
        environment:
          - CLUSTER_NAME=test
        env_file:
          - ./hadoop.env
        extra_hosts:
          - "namenode:172.19.0.2"
          - "datanode1:172.19.0.3"
          - "datanode2:172.19.0.4"
          - "datanode3:172.19.0.5"
          - "historyserver:172.19.0.6"
          - "resourcemanager:172.19.0.7"
          - "nodemanager1:172.19.0.8"
        ports:
          - 50070:50070
    
    resourcemanager:
        image: bde2020/hadoop-resourcemanager:1.1.0-hadoop2.7.1-java8
        container_name: resourcemanager
        depends_on:
          - namenode
          - datanode1
          - datanode2
        env_file:
          - ./hadoop.env
        extra_hosts:
          - "namenode:172.19.0.2"
          - "datanode1:172.19.0.3"
          - "datanode2:172.19.0.4"
          - "datanode3:172.19.0.5"
          - "historyserver:172.19.0.6"
          - "resourcemanager:172.19.0.7"
          - "nodemanager1:172.19.0.8"
        ports:
          - 8032:8032

    historyserver:
        image: bde2020/hadoop-historyserver:1.1.0-hadoop2.7.1-java8
        container_name: historyserver
        depends_on:
          - namenode
          - datanode1
          - datanode2
        volumes:
          - hadoop_historyserver:/hadoop/yarn/timeline
        env_file:
          - ./hadoop.env
        extra_hosts:
          - "namenode:172.19.0.2"
          - "datanode1:172.19.0.3"
          - "datanode2:172.19.0.4"
          - "datanode3:172.19.0.5"
          - "historyserver:172.19.0.6"
          - "resourcemanager:172.19.0.7"
          - "nodemanager1:172.19.0.8"
        ports:
          - 8188:8188

    nodemanager1:
        image: bde2020/hadoop-nodemanager:1.1.0-hadoop2.7.1-java8
        container_name: nodemanager1
        depends_on:
          - namenode
          - datanode1
          - datanode2
        env_file:
          - ./hadoop.env
        extra_hosts:
          - "namenode:172.19.0.2"
          - "datanode1:172.19.0.3"
          - "datanode2:172.19.0.4"
          - "datanode3:172.19.0.5"
          - "historyserver:172.19.0.6"
          - "resourcemanager:172.19.0.7"
          - "nodemanager1:172.19.0.8"
        ports:
          - 8042:8042

    datanode1:
        image: bde2020/hadoop-datanode:1.1.0-hadoop2.7.1-java8
        container_name: datanode1
        depends_on:
          - namenode
        volumes:
          - hadoop_datanode1:/hadoop/dfs/data
        env_file:
          - ./hadoop.env
        extra_hosts:
          - "namenode:172.19.0.2"
          - "datanode1:172.19.0.3"
          - "datanode2:172.19.0.4"
          - "datanode3:172.19.0.5"
          - "historyserver:172.19.0.6"
          - "resourcemanager:172.19.0.7"
          - "nodemanager1:172.19.0.8"
  
    datanode2:
        image: bde2020/hadoop-datanode:1.1.0-hadoop2.7.1-java8
        container_name: datanode2
        depends_on:
          - namenode
        volumes:
          - hadoop_datanode2:/hadoop/dfs/data
        env_file:
          - ./hadoop.env
        extra_hosts:
          - "namenode:172.19.0.2"
          - "datanode1:172.19.0.3"
          - "datanode2:172.19.0.4"
          - "datanode3:172.19.0.5"
          - "historyserver:172.19.0.6"
          - "resourcemanager:172.19.0.7"
          - "nodemanager1:172.19.0.8"
  
    datanode3:
        image: bde2020/hadoop-datanode:1.1.0-hadoop2.7.1-java8
        container_name: datanode3
        depends_on:
          - namenode
        volumes:
          - hadoop_datanode3:/hadoop/dfs/data
        env_file:
          - ./hadoop.env
        extra_hosts:
          - "namenode:172.19.0.2"
          - "datanode1:172.19.0.3"
          - "datanode2:172.19.0.4"
          - "datanode3:172.19.0.5"
          - "historyserver:172.19.0.6"
          - "resourcemanager:172.19.0.7"
          - "nodemanager1:172.19.0.8"

volumes:
    hadoop_namenode:
    hadoop_datanode1:
    hadoop_datanode2:
    hadoop_datanode3:
    hadoop_historyserver:




